### PR TITLE
Update Webkit2

### PR DESCRIPTION
**Pull request by mvaello**
- Updated the Webkit2 to 4.0 version for build the project correctly.
- Removed some unneeded config values.

### CODE REVIEW

**Comment by mcepl** [comment]
Except, after the successful compilation I still get this error (Gnome 3.22, gjs-1.46.0-1.el7.x86_64):
```
matej@mitmanek: ~$ gnome-books 

(gjs-console:15482): Gjs-WARNING **: JS ERROR: Error: Requiring GbPrivate, version none: Typelib file for namespace 'GbPrivate' (any version) not found
@/usr/local/share/books/js/application.js:30
@/usr/local/share/books/js/main.js:20
@<command line>:1

JS_EvaluateScript() failed
matej@mitmanek: ~$
```

**Comment by mvaello** [comment]
Humm, ok. Let me test it again, the commits were done ~2 years ago, and the project is still unmaintained I'm not sure if worth it.

**Comment by mvaello** [comment]
Hi @mcepl, 

First, thank you for your interest on GNOME Books. I'm working on my fork (branch develop) and I realized that with 1.48.5 is still there even many more warings/errors, but with some quick tweaks I could made it starts but using JHBuild instead of building it directly.

So, I recommend you to use JHBuild. First, clone the project into your jhbuild's checkout folder, then try run the autogen.sh as always but prefixing it at your JHBbuild install folder ( for example ./autogen.sh --prefix=~/jhbuild/install) then just run it with $ jhbuild run gnome-books command

Have fun!

**Comment by mvaello** [comment]
Other tip:

``

**Comment by mvaello** [comment]
Other tip, comment or remove the line 160 in the src/application.js file in order to avoid crashing the app

**Comment by mcepl** [comment]
> Other tip, comment or remove the line 160 in the src/application.js file in order to avoid crashing the app

That doesn't help at all, the error is still the same.

**Comment by mcepl** [comment]
> If we keep working on this project, it would be fairly recommended to substitute epub.js by libgepub

is it?

1. I hoped that the Gnome community finally saw the Light and rejected constant push to do everything on its own. It seems to me that JavaScript library used by multiple users is better than yet another home-made library never used by anybody else than other Gnome program.

2. I don't think we have enough brain power free to rewrite gnome-books to new API.

**Comment by mvaello** [comment]
@mcepl sorry, use my branch from my fork the master branch is even more outdated. I can send you a desktop recording with the steps.

Asking to your question:

1. I'm not sure, the tooling is still a lack and even harder situation in GJS. I suggested libgepub because it looks like more maintained this days and could be added easily as a dependencie in the project. 

2. The probem here, IMHO, is there is no much interest from GNOME to supporting this kind of apps. There is no official code hosting, no official bugtracking or whatever. I'm interested on the project, but of course there is many things that should be rethinked or even missing features that should be added to become useful.
If you whant to share ideas mail/IRC me https://wiki.gnome.org/MiguelVaello

**Pull request closed without merging**
